site_name: My Docs
site_url: https://note.thinkingbuilder.cc
repo_name: Thinking-builder/notebook  #存储库名称，一般自动设置
repo_url: https://github.com/Thinking-builder/Noteweb #存储库URL
site_discription: Thinking_Builder的笔记
nav:
  - Home: index.md
  - Language:
      - easy markdown: easy markdown.md
      - mkdocs_start: mkdocs_2.md
      - C++:
          - C++ tip: C++_debug_record.md
          - C++ 进阶: C++_primer.md
  - tools:
      - Shell: shell.md
      - Vim: vim.md
  - CS:
      - CS Crash Course: CS_basical_knowledge.md
  - Hobby Field:
      - 手机摄影: Photo.md

markdown_extensions:
  - toc:
      permalink: True
  - admonition
  - pymdownx.details
  - pymdownx.superfences

theme:
  name: material
  logo: /logo.png
  features:
    - search.highlight
    - navigation.tabs

  palette:
    # Palette toggle for light mode
    - scheme: default
      primary: white
      accent: light blue
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      primary: black
      accent: deep purple
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
